// Static catalogue. CodeBuddy exposes no live model list, so this ships as a
// curated table — revised 2026-09-14 from the official workbuddy.ai catalogue
// (id, display name, context, output, credit multiplier, reasoning/thinking
// flags, effort levels, image + tool-call support).

import type { ModelInfo } from "./types";

export const codebuddyModels: ModelInfo[] = [
  {
    id: "default-model",
    name: "Auto ⭐default",
    maxInputTokens: 176_000,
    maxOutputTokens: 24_000,
    creditMultiplier: 1,
    images: true,
    toolCalls: true,
  },
  {
    id: "fast-model",
    name: "Fast",
    maxInputTokens: 200_000,
    maxOutputTokens: 32_000,
    creditMultiplier: 0.34,
    thinking: true,
    thinkingToggle: "onlyReasoning",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "balanced-model",
    name: "Balanced",
    maxInputTokens: 256_000,
    maxOutputTokens: 32_000,
    creditMultiplier: 0.59,
    thinking: true,
    thinkingToggle: "onlyReasoning",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "primary-model",
    name: "Primary",
    maxInputTokens: 272_000,
    maxOutputTokens: 72_000,
    creditMultiplier: 3.31,
    thinking: true,
    thinkingToggle: "onlyReasoning",
    effort: "low→xhigh", // verified: "max" rejected upstream (11133)
    images: true,
    toolCalls: true,
  },
  {
    id: "deep-model",
    name: "Deep",
    maxInputTokens: 176_000,
    maxOutputTokens: 24_000,
    creditMultiplier: 3.33,
    images: true,
    toolCalls: true,
  },
  // ── Claude family (kept per LO — still served upstream) ────────
  { id: "claude-sonnet-4.6", maxInputTokens: 176_000, maxOutputTokens: 24_000, ownedBy: "anthropic", thinking: true, effort: "low→max (5 level)", images: true, toolCalls: true },
  { id: "claude-opus-5", maxInputTokens: 1_000_000, maxOutputTokens: 128_000, ownedBy: "anthropic", thinking: true, effort: "low→max (5 level)", images: true, toolCalls: true },
  { id: "claude-opus-4.7-1m", maxInputTokens: 1_000_000, maxOutputTokens: 128_000, ownedBy: "anthropic", thinking: true, effort: "low→max (5 level)", images: true, toolCalls: true },
  { id: "claude-opus-4.6", name: "Claude Opus 4.6", maxInputTokens: 1_000_000, maxOutputTokens: 128_000, ownedBy: "anthropic", thinking: true, effort: "low→max (5 level)", images: true, toolCalls: true },
  {
    id: "deepseek-v4.1-flash",
    name: "Deepseek-V4.1-Flash",
    maxInputTokens: 1_000_000, // 300K default
    maxOutputTokens: 128_000,
    ownedBy: "deepseek",
    creditMultiplier: 0, // 🆓 free until 2026-09-25
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  { id: "deepseek-v3-0324", maxInputTokens: 128_000, maxOutputTokens: 8_192, ownedBy: "deepseek", images: true, toolCalls: true },
  {
    id: "gpt-6-astra",
    name: "GPT-6-Astra",
    maxInputTokens: 1_000_000, // 400K default
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    creditMultiplier: 6.67,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "hy4-preview-f",
    name: "Hy4 preview F",
    maxInputTokens: 1_000_000, // 300K default
    maxOutputTokens: 64_000,
    ownedBy: "tencent",
    creditMultiplier: 0, // 🆓 free until 2026-10-10
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "hy4-preview",
    name: "Hy4 preview",
    maxInputTokens: 1_000_000, // 200K default
    maxOutputTokens: 64_000,
    ownedBy: "tencent",
    creditMultiplier: 0.29,
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "hy3",
    name: "Hy3",
    maxInputTokens: 192_000,
    maxOutputTokens: 64_000,
    ownedBy: "tencent",
    creditMultiplier: 0, // 🆓 free unlimited until 2026-09-30
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT-5.6-Sol",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    creditMultiplier: 3.47,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (flaky 11134)", // 11134 errors intermittently at every level
    images: true,
    toolCalls: false,
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT-5.6-Terra",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    creditMultiplier: 1.39,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT-5.6-Luna",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    creditMultiplier: 0.14,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "gpt-5.5",
    name: "GPT-5.5",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    creditMultiplier: 3.31,
    thinking: true,
    effort: "low→xhigh", // verified: "max" rejected upstream (11133)
    images: true,
    toolCalls: true,
  },
  {
    id: "gpt-5.4",
    name: "GPT-5.4",
    maxInputTokens: 272_000,
    maxOutputTokens: 72_000,
    ownedBy: "openai",
    creditMultiplier: 1.64,
    thinking: true,
    effort: "low→xhigh", // verified: "max" rejected upstream (11133)
    images: true,
    toolCalls: true,
  },
  {
    id: "gemini-3.5-flash",
    name: "Gemini-3.5-Flash",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 65_000,
    ownedBy: "google",
    creditMultiplier: 0.12,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "gemini-3.1-pro",
    name: "Gemini-3.1-Pro",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 64_000,
    ownedBy: "google",
    images: true,
    toolCalls: true,
  },
  {
    id: "glm-5.3",
    name: "GLM-5.3",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 48_000,
    ownedBy: "zhipu",
    creditMultiplier: 0.79,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "glm-5.2",
    name: "GLM-5.2",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 48_000,
    ownedBy: "zhipu",
    creditMultiplier: 0.79,
    thinking: true,
    thinkingToggle: "canDisable",
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "gpt-5.3-codex",
    name: "GPT-5.3-Codex",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 128_000,
    ownedBy: "openai",
    thinking: true,
    effort: "low→xhigh", // verified: "max" rejected upstream (11133)
    images: true,
    toolCalls: true,
  },
  {
    id: "kimi-k3",
    name: "Kimi-K3",
    maxInputTokens: 1_000_000,
    maxOutputTokens: 32_000,
    ownedBy: "moonshot",
    creditMultiplier: 1.62,
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  {
    id: "kimi-k2.6",
    name: "Kimi-K2.6",
    maxInputTokens: 256_000,
    maxOutputTokens: 32_000,
    ownedBy: "moonshot",
    creditMultiplier: 0.52,
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  // ── Kept per LO ───────────────────────────────────────────────
  { id: "kimi-k2.5", maxInputTokens: 164_000, maxOutputTokens: 32_000, ownedBy: "moonshot", thinking: true, images: true, toolCalls: true },
  {
    id: "kimi-k2.8-preview",
    name: "Kimi-K2.8 (preview)",
    maxInputTokens: 256_000,
    maxOutputTokens: 32_000,
    ownedBy: "moonshot",
    thinking: true,
    effort: "low→max (5 level)",
    images: true,
    toolCalls: true,
  },
  { id: "minimax-m3", maxInputTokens: 512_000, maxOutputTokens: 48_000, ownedBy: "minimax", images: true, toolCalls: true },

  // ── Image generation (kind: "image") ──────────────────────────
  // Live-probed 2026-09-15: POST /v2/images/generations returns 200 with a
  // Tencent COS URL in the response. Chat endpoints reject or misroute these
  // ids, so they only serve /v1/images/generations.
  { id: "gpt-image-2", name: "GPT Image 2", ownedBy: "openai", kind: "image" },
  { id: "gemini-2.5-flash-image", name: "Gemini 2.5 Flash Image", ownedBy: "google", kind: "image" },
  { id: "gemini-3.1-flash-image", name: "Gemini 3.1 Flash Image", ownedBy: "google", kind: "image" },
];
